apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/Bolasto/capstone_PJ.git
    targetRevision: HEAD
    ref: bolastorepo
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.5
    # helm:
    #   values: |
    #     service:
    #       type: LoadBalancer
    #     datasources:
    #       datasources.yaml:
    #         apiVersion: 1
    #         datasources:
    #         - name: Prometheus
    #           type: prometheus
    #           url: http://prometheus-server
    #           access: proxy
    #           isDefault: true
    #     dashboardProviders:
    #       dashboardproviders.yaml:
    #         apiVersion: 1
    #         providers:
    #         - name: 'default'
    #           orgId: 1
    #           folder: ''
    #           type: file
    #          disableDeletion: false
    #           editable: true
    #           options:
    #             path: /var/lib/grafana/dashboards/default
    #     dashboards:
    #       default:
    #         kubernetes:
    #           gnetId: 10000
    #           revision: 1
    #           datasource: Prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
