apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/Bolasto/capstone_PJ.git
    targetRevision: HEAD
    ref: bolastorepo
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.5
    helm:
      values: |
        service:
          type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
