apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.19.0
    helm:
      values: |
        loki:
          ingester:
            autoforget_unhealthy: true
          limits_config:
            retention_period: 744h
            reject_old_samples: true
            reject_old_samples_max_age: 744h   
          auth_enabled: false
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 2
          schema_config:
            configs:
            - from: "2022-01-11"
              index:
                period: 24h
                prefix: loki_index_
              store: boltdb-shipper
              object_store: s3
              schema: v12
          storage_config:
            aws:
              bucketnames: capspjbuc
              s3forcepathstyle: false
              region: us-east-1 
            boltdb_shipper:
              active_index_directory: /var/loki/index
              shared_store: s3
          rulerConfig:
            storage:
              type: local
              local:
                directory: /var/loki/rules
        gateway:
          autoscaling:
           enabled: true
           minReplicas: 1
           maxReplicas: 2
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          alerts:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: true
            lokiCanary:
              enabled: false
            grafanaAgent:
              installOperator: false
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::058264418288:role/lokibuc
        ingress:
          enabled: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
